runners:
  local_runner:
    load: galaxy.jobs.runners.local:LocalJobRunner
    workers: 4

execution:
  default: local_dest
  environments:
    local_dest:
      runner: local_runner
    tf_dest:
      runner: local_runner

limits:
- type: "destination_total_concurrent_jobs"
  id: "tf_dest"
  value: "1"

tools:
- id: toolfactory
  destination: tf_dest

# this is for the toolfactory so only one test runs at a time using galaxy_tool_test
# dev 23.0 gives >50% of 16 jobs crash and burn if the test workflow runs many at once.
# Postgres makes no difference.
# Galaxy was not designed to allow a tool to run tests and there's some leakage/race problems.
